/**
 * BUILD THE SINGLE BINARY (spike, 2026-10-09 — docs/notes/single-binary-spike.md).
 *
 *   ~/.bun/bin/bun tools/single-binary/build.ts [--target bun-darwin-arm64,…|all] [--bytecode] [--out dist/single-binary]
 *
 * 1. Copies every file the running code reads from its own install —
 *    package.json (the version), the model table's package, the dashboard's
 *    page and static modules, and the licences that travel with vendored code —
 *    into a STAGE that mirrors the repository's layout, and writes
 *    `assets.gen.ts`: one `import … with { type: "file" }` per staged file.
 *    With `--root <stage>`, `bun build --compile` embeds each at its
 *    repository-relative path under the binary's virtual root, which is where
 *    `adapters/runtime.ts#packagePath` looks. The copy is not ceremony: a file
 *    that is ALSO imported as code (`web/shared/dates.js`, by `narrate.ts`)
 *    cannot be imported as a file from the same path — Bun keeps one loader
 *    per path ("No matching export … for import dateOr").
 * 2. Compiles `main.ts` once per target, with the runtime's cwd autoloads OFF:
 *    a hook runs in the person's project, and a compiled Bun binary would
 *    otherwise read that project's `.env` and `bunfig.toml` into itself.
 * 3. Writes `SHA256SUMS` beside the binaries, and a gzip of each (what a
 *    release would upload), and prints raw and gzipped sizes.
 */
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { gzipSync } from "node:zlib";

const REPO = resolve(import.meta.dir, "../..");
const HERE = import.meta.dir;

export const ALL_TARGETS = [
  "bun-darwin-arm64",
  "bun-darwin-x64",
  "bun-linux-x64",
  "bun-linux-arm64",
  "bun-windows-x64",
] as const;

/** Every file the code reads from its own install at run time. */
export function embeddedFiles(): string[] {
  const out: string[] = ["package.json"];
  const model = "node_modules/counterparts-model-potion";
  for (const f of ["model.safetensors", "vocab.txt", "package.json", "LICENSE"]) out.push(`${model}/${f}`);
  const web = "src/adapters/dashboard/web";
  out.push(`${web}/app.html`, `${web}/app.js`);
  const walk = (dir: string): void => {
    for (const name of readdirSync(join(REPO, dir)).sort()) {
      const rel = `${dir}/${name}`;
      if (statSync(join(REPO, rel)).isDirectory()) walk(rel);
      else if (/\.(js|css|woff2|txt)$/.test(name)) out.push(rel);
    }
  };
  for (const d of ["shared", "shell", "pages", "mechanisms"]) walk(`${web}/${d}`);
  return out;
}

function stageAndWriteManifest(files: readonly string[], stage: string): void {
  rmSync(stage, { recursive: true, force: true });
  for (const f of files) {
    mkdirSync(dirname(join(stage, f)), { recursive: true });
    copyFileSync(join(REPO, f), join(stage, f));
  }
  const lines = [
    "// @ts-nocheck — data imports, not code; typechecking them is noise.",
    "// GENERATED by tools/single-binary/build.ts — do not edit, not committed.",
    "// Each import embeds one file in the compiled binary (`with { type: \"file\" }`).",
    ...files.map((f, i) => `import f${String(i)} from ${JSON.stringify(relative(HERE, join(stage, f)))} with { type: "file" };`),
    `export const EMBEDDED: readonly string[] = [${files.map((_, i) => `f${String(i)}`).join(", ")}];`,
    "",
  ];
  writeFileSync(join(HERE, "assets.gen.ts"), lines.join("\n"));
}

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

if (import.meta.main) {
  const targetsArg = arg("--target") ?? "native";
  const targets = targetsArg === "all" ? [...ALL_TARGETS] : targetsArg.split(",");
  const outDir = resolve(REPO, arg("--out") ?? "dist/single-binary");
  const bytecode = process.argv.includes("--bytecode");
  const version = (JSON.parse(readFileSync(join(REPO, "package.json"), "utf8")) as { version: string }).version;
  mkdirSync(outDir, { recursive: true });

  const files = embeddedFiles();
  const stage = join(outDir, "stage");
  stageAndWriteManifest(files, stage);
  process.stdout.write(`embedding ${String(files.length)} files\n`);

  const sums: string[] = [];
  for (const target of targets) {
    const name = `counterparts-${version}-${target === "native" ? "native" : target.replace(/^bun-/, "")}${target.includes("windows") ? ".exe" : ""}`;
    const outfile = join(outDir, name);
    const args = [
      "build",
      "--compile",
      ...(target === "native" ? [] : [`--target=${target}`]),
      `--root=${stage}`,
      "--asset-naming=[dir]/[name].[ext]",
      "--no-compile-autoload-dotenv",
      "--no-compile-autoload-bunfig",
      ...(bytecode ? ["--bytecode", "--format=esm"] : []),
      `--outfile=${outfile}`,
      join(HERE, "main.ts"),
    ];
    const t0 = performance.now();
    const res = spawnSync(process.execPath, args, { cwd: REPO, encoding: "utf8" });
    const ms = Math.round(performance.now() - t0);
    if (res.status !== 0) {
      process.stdout.write(`${target}: FAILED (${String(res.status)})\n${res.stdout}${res.stderr}\n`);
      continue;
    }
    const bytes = readFileSync(outfile);
    const gz = gzipSync(bytes, { level: 9 });
    writeFileSync(`${outfile}.gz`, gz);
    const sha = createHash("sha256").update(bytes).digest("hex");
    const shaGz = createHash("sha256").update(gz).digest("hex");
    sums.push(`${sha}  ${name}`, `${shaGz}  ${name}.gz`);
    const mib = (n: number): string => (n / 1024 / 1024).toFixed(1);
    process.stdout.write(`${target}: ${mib(bytes.length)} MiB raw, ${mib(gz.length)} MiB gz, ${String(ms)} ms -> ${relative(REPO, outfile)}\n`);
  }
  writeFileSync(join(outDir, "SHA256SUMS"), `${sums.join("\n")}\n`);
}
